import type { NodeSpecRegistry } from '../_types';

export const NODE_SPECS = {
  INPUT: {
    TEXT_INPUT: {
      in_edge_arguments: [],
      node_arguments: [
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'Hello, world',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'value',
        },
      ],
      node_info: {
        node_group: 'INPUT',
        node_type: 'TEXT_INPUT',
        node_uid: 'N_001',
      },
      node_requirement: {
        max_in_edges: 0,
        max_out_edges: 100,
        min_in_edges: 0,
        min_out_edges: 1,
        valid_inputs: [],
        valid_outputs: ['MODEL', 'OUTPUT'],
      },
      out_edge_arguments: [],
    },
    FILE_INPUT: {
      in_edge_arguments: [],
      node_arguments: [
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'csv',
          have_options: true,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'format',
          options: ['csv', 'json', 'txt'],
        },
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'name,score\nAda,90\nAlan,77',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'content',
        },
      ],
      node_info: {
        node_group: 'INPUT',
        node_type: 'FILE_INPUT',
        node_uid: 'N_002',
      },
      node_requirement: {
        max_in_edges: 0,
        max_out_edges: 100,
        min_in_edges: 0,
        min_out_edges: 1,
        valid_inputs: [],
        valid_outputs: ['MODEL', 'OUTPUT'],
      },
      out_edge_arguments: [],
    },
    WEBHOOK: {
      in_edge_arguments: [],
      node_arguments: [
        {
          argument_type: 'TEXT',
          children: {},
          default_value: '{\n  "event": "signup",\n  "user": "ada"\n}',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'payload',
        },
      ],
      node_info: {
        node_group: 'INPUT',
        node_type: 'WEBHOOK',
        node_uid: 'N_003',
      },
      node_requirement: {
        max_in_edges: 0,
        max_out_edges: 100,
        min_in_edges: 0,
        min_out_edges: 1,
        valid_inputs: [],
        valid_outputs: ['MODEL', 'OUTPUT'],
      },
      out_edge_arguments: [],
    },
  },
  MODEL: {
    LLM: {
      in_edge_arguments: [],
      node_arguments: [
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'anthropic',
          have_options: true,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: true,
          name: 'provider',
          options: ['anthropic', 'openai', 'deepseek'],
        },
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'claude-sonnet-5',
          have_options: true,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'model',
          options: [
            'claude-sonnet-5',
            'claude-haiku-4-5-20251001',
            'claude-opus-4-8',
            'claude-fable-5',
          ],
        },
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'Reply with one word.\n{{input}}',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: true,
          name: 'prompt',
        },
        {
          argument_type: 'TEXT',
          children: {},
          default_value: '',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'system',
        },
        {
          argument_type: 'NUMBER',
          children: {},
          default_value: 1024,
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'max_tokens',
        },
      ],
      node_info: {
        node_group: 'MODEL',
        node_type: 'LLM',
        node_uid: 'N_005',
      },
      node_requirement: {
        max_in_edges: 100,
        max_out_edges: 100,
        min_in_edges: 1,
        min_out_edges: 1,
        valid_inputs: ['INPUT', 'MODEL'],
        valid_outputs: ['MODEL', 'OUTPUT'],
      },
      out_edge_arguments: [],
    },
    EMBEDDING: {
      in_edge_arguments: [],
      node_arguments: [
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'text-embedding-3-small',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'model',
        },
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'text',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'input_column',
        },
      ],
      node_info: {
        node_group: 'MODEL',
        node_type: 'EMBEDDING',
        node_uid: 'N_006',
      },
      node_requirement: {
        max_in_edges: 100,
        max_out_edges: 100,
        min_in_edges: 1,
        min_out_edges: 1,
        valid_inputs: ['INPUT', 'MODEL'],
        valid_outputs: ['MODEL', 'OUTPUT'],
      },
      out_edge_arguments: [],
    },
    CLASSIFIER: {
      in_edge_arguments: [],
      node_arguments: [
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'positive,negative,neutral',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: true,
          name: 'labels',
        },
        {
          argument_type: 'TEXT',
          children: {},
          default_value: 'text',
          have_options: false,
          have_sub_arguments: false,
          is_deprecated: false,
          is_hidden: false,
          is_list: false,
          is_required: false,
          name: 'input_column',
        },
      ],
      node_info: {
        node_group: 'MODEL',
        node_type: 'CLASSIFIER',
        node_uid: 'N_007',
      },
      node_requirement: {
        max_in_edges: 100,
        max_out_edges: 100,
        min_in_edges: 1,
        min_out_edges: 1,
        valid_inputs: ['INPUT', 'MODEL'],
        valid_outputs: ['MODEL', 'OUTPUT'],
      },
      out_edge_arguments: [],
    },
  },
  OUTPUT: {
    DISPLAY: {
      in_edge_arguments: [],
      node_arguments: [],
      node_info: {
        node_group: 'OUTPUT',
        node_type: 'DISPLAY',
        node_uid: 'N_008',
      },
      node_requirement: {
        max_in_edges: 100,
        max_out_edges: 0,
        min_in_edges: 1,
        min_out_edges: 0,
        valid_inputs: ['INPUT', 'MODEL'],
        valid_outputs: [],
      },
      out_edge_arguments: [],
    },
    LOG: {
      in_edge_arguments: [],
      node_arguments: [],
      node_info: {
        node_group: 'OUTPUT',
        node_type: 'LOG',
        node_uid: 'N_009',
      },
      node_requirement: {
        max_in_edges: 100,
        max_out_edges: 0,
        min_in_edges: 1,
        min_out_edges: 0,
        valid_inputs: ['INPUT', 'MODEL'],
        valid_outputs: [],
      },
      out_edge_arguments: [],
    },
  },
} satisfies NodeSpecRegistry;
